### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by birkof** [Olivier127/rbac-bundle#11]
Currently, Composer limits us to Symfony 6 only.

@ Olivier127 as you know, are there any incompatibilities when upgrading?

**Comment by Olivier127** [comment]
Hi @birkof , I haven't tested with SF 7 yet, but I think there shouldn't be any issues. I just need to confirm that.

**Comment by Olivier127** [comment]
It's merged, however, I have an error in Symfony 7. It seems that the DoctrineResolveTargetEntityPass no longer works.

**Comment by Olivier127** [comment]
it works with this configuration : 
```
#config/package/doctrine.yaml
doctrine:
    orm:
        resolve_target_entities:
            PhpRbacBundle\Entity\RoleInterface: App\Entity\Role
            PhpRbacBundle\Entity\PermissionInterface: App\Entity\Permission
```

**Comment by birkof** [comment]
In that case, we'll need to get rid of "permission", "role", "user" options, and to make them dynamically defined.

**Comment by Olivier127** [comment]
I have updated the compiler, it works now
