### ISSUE TITLE
Table names

### ISSUE THREAD

**Issue by alexbogo** [Olivier127/rbac-bundle#2]
Hi,

This is not an issue but a question...
Is it possible to change the table names? And how I would do this?
I can see that you are referencing the repositories in your code, that are in the bundle...
I would like to use my own entities... for example, my role_permission table is called - sysuser_role_association. inherited DB.. so I can't change the names... 

Is this possible?

**Comment by Olivier127** [comment]
Hello,

Symfony creates automatically the table with the name of the entities.

You can change by specify the table name inside the Entity like `#[ORM\Table(name: "the_great_permissions")]` before the class name

**Comment by alexbogo** [comment]
HI, yes, I know that, but in that case I need to change the code in your bundle, which I don’t think is a good practice. If you release update, it will be overwritten.

Cheers
Alex

**Comment by Olivier127** [comment]
Hello, I have modified the core to let you use your own entities.

The version 0.2.0 is here

**Comment by alexbogo** [comment]
Hi Oliver,

Thank you so much, that is great.
I’ll let you know how it goes.

Regards
Alex

**Comment by alexbogo** [comment]
Sorry, I know it’s closed… but just to let you  know that is working fine. 

Cheers
Alex

**Comment by Olivier127** [comment]
That's great ! the next step for this project is to create a rbac security access voter. When i will have time.

**Comment by alexbogo** [comment]
Hi, I am happy to test any new development, if you need help with testing in real world app.
Let me know…

Cheers 
Alex
