### ISSUE TITLE
Parent ID

### ISSUE THREAD

**Issue by alexbogo** [Olivier127/rbac-bundle#3]
Hi,

After updating to the latest version, getting an error on adding a new role:

 SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.parent_id' in 'field list'  

Also, I have noticed that column names have changed from  'left' and 'right' to tree_left and tree_right.

Please advise how to fix it without changing the bundle code. Or if you can create a patch to fix it.  

Thank you.

**Comment by alexbogo** [comment]
Hi, 

Initiating roles and permissions also doesn't work... 
I think that some of the new code is referencing old column names and some new column names... 
Like code -> now title... and left -> tree_left... 

Running security:rbac:install gives:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'code' in 'field list'

I did rename the fields in DB manually... but I may need to run doctrine... 

Thanks

**Comment by Olivier127** [comment]
ok, i'm going to test on fresh symfony

**Comment by alexbogo** [comment]
Thank you

**Comment by alexbogo** [comment]
Hi,

A little bit more info, I have removed the bundle and installed it fresh, running: bin/console doctrine:migration:diff
gives error:

There is no column with name "code" on table "role". 

I did remove all my code ( mainly checks in controllers ) ...

Hope this helps.

**Comment by Olivier127** [comment]
try bin/console doctrine:schema:update -f

I have fixed the code (the security helpe is useless inside the voter). Right et Left inside repository is fixed too.

the column title is rename to code, right to tree_right and left to tree_left.

**Comment by alexbogo** [comment]
Hi, sorry for more issues.
Just installed on totally fresh Symfony and empty DB
Running doctrine DIF generated the migration and tables are created.
But running "security:rbac:install" to initiate the roles/permissions... 
gives this error:

➜  rback git:(main) ✗ bin/console security:rbac:install
 ! [NOTE] Role permission installation
In ExceptionConverter.php line 114:
  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value
In Exception.php line 28:
  SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value
In Connection.php line 69:
  SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value

Sorry... 

Also:

➜  rback git:(main) ✗ bin/console security:rbac:role:add
Enter the code of the role : root
Enter the description of the role : this is root
In ChoiceQuestion.php line 36:
  Choice question must have at least 1 choice available.

Alex

PS
I'll try to install fresh code with your latest changes

**Comment by alexbogo** [comment]
Hi,

I think that "commands" are not adding a title ( only code ) but the "role" and "permission" "title" field definition doesn't allow NULL for "title" fields. 

I think that the rest is fine. 

Thanks
Alex

**Comment by alexbogo** [comment]
Hi,

Sorry, one more... testing commands... 

I've changed the NULL definition for the tables ( just to test it ) and it installed the initial root role. 
But when adding an additional role, when asked for the parent ID, I specified root, but "parent_id" wasn't populated in the role table.  The jojo role should have parent_id = 1

1	null		root	root	0	3
2	nill		this jojo role	jojo	1	2

**Comment by Olivier127** [comment]
Thanx ;) have a good sleep.

i have remove all title mention in the code. Do you get the right version (dev-main) of the code ? 

> But when adding an additional role, when asked for the parent ID, I specified root, but "parent_id" wasn't populated in the role table. The jojo role should have parent_id = 1
> 
> 1 null root root 0 3
> 2 null this jojo role jojo 1 2

it's fixed :)

Thanks a lot for your issues

**Comment by alexbogo** [comment]
Hi,

Unfortunately, still not working. The "NULL" value error for the title, in the role and  permission tables, the default value is still NOT NULL,  and now this error:
  rback git:(main) ✗ bin/console security:rbac:role:add

In QueryException.php line 43:
  [Semantical Error] line 0, col 181 near 'tree_left BETWEEN': Error: Class App\Entity\Security\Role has no field or association named tree_left
In QueryException.php line 21:

  SELECT
                  parent
              FROM
                  App\Entity\Security\Role parent
              JOIN
                  App\Entity\Security\Role node WITH node.tree_left BETWEEN parent.tree_left AND parent.tree_right
              WHERE
                  node.id = :nodeId
              ORDER BY
                  parent.tree_left
security:rbac:role:add

I am using MySQL 8 and PHP 8.1 

Thanks

**Comment by alexbogo** [comment]
It looks like only the add role has issues. This is when adding a role from the controller.
[Semantical Error] line 0, col 181 near 'tree_left BETWEEN': Error: Class App\Entity\Security\Role has no field or association named tree_left

This is when using "manager" in the controller, adding permission works fine, well, it added the permission but didn't try to link it to the role yet...

Cheers

**Comment by alexbogo** [comment]
My entities do extend your classes:
use Doctrine\ORM\Mapping as ORM;
use PhpRbacBundle\Entity\Role as EntityRole;
use PhpRbacBundle\Repository\RoleRepository;

#[ORM\Entity(repositoryClass: RoleRepository::class)]
class Role extends EntityRole

And the field is there...

use Doctrine\ORM\Mapping as ORM;
use PhpRbacBundle\Entity\Permission as EntityPermission;
use PhpRbacBundle\Repository\PermissionRepository;

#[ORM\Entity(repositoryClass: PermissionRepository::class)]
#[ORM\Table('permission')]
class Permissions  extends EntityPermission

**Comment by Olivier127** [comment]
> My entities do extend your classes: use Doctrine\ORM\Mapping as ORM; use PhpRbacBundle\Entity\Role as EntityRole; use PhpRbacBundle\Repository\RoleRepository;
> 
> #[ORM\Entity(repositoryClass: RoleRepository::class)] class Role extends EntityRole
> 
> And the field is there...
> 
> use Doctrine\ORM\Mapping as ORM; use PhpRbacBundle\Entity\Permission as EntityPermission; use PhpRbacBundle\Repository\PermissionRepository;
> 
> #[ORM\Entity(repositoryClass: PermissionRepository::class)] #[ORM\Table('permission')] class Permissions extends EntityPermission

so your 'title' field is here ?

**Comment by Olivier127** [comment]
sample of my extended entities
[Entity.zip](https://github.com/Olivier127/rbac-bundle/files/10416787/Entity.zip)

**Comment by alexbogo** [comment]
Hi,

I have removed all methods in my entities, for testing purposes. They are same as yours. Only difference is that my entities are one more folder dipper. App\Entity\Security...  and mapped in config yamal file:

php_rbac:
  no_authentication_section:
    default: deny
  resolve_target_entities:
    role: App\Entity\Security\Role
    permission: App\Entity\Security\Permissions

When running example code in controller:

    #[Route('/test', name: 'app_test')]
    public function index(PermissionManager $manager, RoleManager $roleManager): Response
    {
        
        $roleManager->addPath("/editor/reviewer", ['editor' => 'Editor', 'reviewer' => "Reviewer"]);

 getting error:

[Semantical Error] line 0, col 46 near 'right = node.right': Error: Class App\Entity\Security\Role has no field or association named right


Entities:

<?php

namespace App\Entity\Security;

use Doctrine\ORM\Mapping as ORM;
use PhpRbacBundle\Entity\Role as EntityRole;
use PhpRbacBundle\Repository\RoleRepository;

#[ORM\Entity(repositoryClass: RoleRepository::class)]
class Role extends EntityRole
{

}


<?php

namespace App\Entity\Security;

use Doctrine\ORM\Mapping as ORM;
use PhpRbacBundle\Entity\Permission as EntityPermission;
use PhpRbacBundle\Repository\PermissionRepository;

#[ORM\Entity(repositoryClass: PermissionRepository::class)]
#[ORM\Table('permission')]
class Permissions  extends EntityPermission
{

}

Thanks

**Comment by alexbogo** [comment]
this is the SQL to be executed..
SELECT parent FROM App\Entity\Security\Role parent JOIN App\Entity\Security\Role node WITH node.tree_left BETWEEN parent.tree_left AND parent.tree_right WHERE node.id = :nodeId ORDER BY parent.tree_left

Error:

[Semantical Error] line 0, col 181 near 'tree_left BETWEEN': Error: Class App\Entity\Security\Role has no field or association named tree_left

**Comment by Olivier127** [comment]
i have pushed fix for the tree_right and tree_left stil inside code. I'm in front of my right computer ^^.

I have pushed the phpunit too

**Comment by alexbogo** [comment]
OK, I have changed the Node entity and renamed $left and $right to $tree_left and $tree_right... Doctrine will look into var names in queries, not field names... regardless of what the DB field name is.  That fixed the first problem. Now the update query is failing with 

UPDATE App\Entity\Security\Role node SET node.right = node.right + 2 WHERE node.right >= :right

Because in this query - field names are left and right... 

The problem is in field naming in queries...

OK, I'll check out the latest code, still dev_main?

**Comment by alexbogo** [comment]
Haha... I have only one screen... :(

**Comment by alexbogo** [comment]
Installed the latest code, and the first test succeeded...
I'll do some more tests and let you know... 

Thank you for the fixes...  

Cheers
Alex

**Comment by Olivier127** [comment]
Yep, the tests are running. I have detected a mistake in relationship with parent. It is fixed.

Thanks a lot ;)

**Comment by Olivier127** [comment]
I close this ticket.

**Comment by alexbogo** [comment]
Hi, yes, sorry… should have told you that all is working now.
Thank you again for the awesome support.

Alex
