### ISSUE TITLE
RBAC in Twig

### ISSUE THREAD

**Issue by alexbogo** [Olivier127/rbac-bundle#4]
Hi,

Is there a way to check the RBAC role/permission in twig, through {{ app.user }}?
Or any other way? 

Thanks
Alex

**Comment by Olivier127** [comment]
If you use the voter you can use is_granted('/the/permission') which comes from symfony.
My code has two twig function

- hasRole('/the/role/') 
- hasPermission('/the/permission')

**Comment by alexbogo** [comment]
Hi, sorry, that was a very stupid question... Of course, there's even a Twig extension in the bundle... 
However, I think that I don't understand this, or I am setting things the wrong way...

I have 4 roles. root, super-admin, admin, user
I want to separate my permissions per "objects" ( meaning the group of functions that are allowed on the "Student" object, for example ). I have a number of objects in the app, if I try to set:
/object1/read/write/delete - is done, if I try to add /object2/read/write/delete, I am getting an error, that the parent id must be unique ( root ). 

The reason is that the same user can have different permission for one object e.g full access to object1 but only read to object2... root should have full access to all... 

For example, supper-admin should have all actions on object1, but at the same time, supper-admin should have only read rights on object2... 

How I can do this or do I need to do some more reading, doing it the wrong way? 

P.S.

In the https://phprbac.net/ table permission doesn't have parentID  -  just trying to understand it. 

Sorry for the silly questions... 

Thank you.

**Comment by Olivier127** [comment]
do you use the last "dev-main" ? seems to be a previous bug

le tree of permission will be better as

/object1/read
/object1/write
/object1/delete
/object2/read
/object2/write
/object2/delete

and you associate the role / to the permission /
/admin to /object1 and /object2
/user to /object1/read, /object2/read and /object2/write for example.

I will try to test. Have you a github repository for me to test your code ?

**Comment by Olivier127** [comment]
or /object1/write/delete/read maybe is better (if you have the write permission, you can delete and read, if you have the read permission you can only read).

**Comment by alexbogo** [comment]
Hi,

Thank you for looking into this. 
Yes the branch is:  "olivier127/rbac-bundle": "dev-main"

I'll try to set it up as you suggested. Unfortunately, can't provide the code as the app is commercial and the code is on BitBucket. 

I think that I may have old table metadata in DB. Will compare what is in the code.  I may just remove the constraint... 

Thank you again. I'll let you know how it goes. 

Cheers
Alex

**Comment by alexbogo** [comment]
Hi,

Can you send me the full SQL to create tables, please? 

Thanks

**Comment by alexbogo** [comment]
Hi,

I've just done fresh install on my local machine, and SQL for permissions is as follows, with UNIQUE Index on parent ID...
CREATE TABLE permission (
	id INT AUTO_INCREMENT NOT NULL,
	parent_id INT DEFAULT NULL,
	title VARCHAR ( 255 ) NOT NULL,
	description VARCHAR ( 255 ) NOT NULL,
	CODE VARCHAR ( 255 ) NOT NULL,
	tree_left INT NOT NULL,
	tree_right INT NOT NULL,
	**UNIQUE INDEX UNIQ_E04992AA727ACA70 ( parent_id ),**
	INDEX permission_idx ( CODE, tree_left, tree_right ),
	UNIQUE INDEX unique_code ( CODE, parent_id ),
PRIMARY KEY ( id )) DEFAULT CHARACTER 

Is this correct? If it is, examples you provided wouldn't work.

**Comment by alexbogo** [comment]
Hi,

Fresh install, after creating all tables, running security:rbac:install: 

An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value

**Comment by Olivier127** [comment]
I have done a fresh install and my sql dump is this :
```sql
CREATE TABLE `my_permissions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT NULL,
  `code` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tree_left` int(11) NOT NULL,
  `tree_right` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_code` (`code`,`parent_id`),
  KEY `IDX_DF784827727ACA70` (`parent_id`),
  KEY `permission_idx` (`code`,`tree_left`,`tree_right`),
  CONSTRAINT `FK_DF784827727ACA70` FOREIGN KEY (`parent_id`) REFERENCES `my_permissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by Olivier127** [comment]
i have made the 0.3.0 release. Can you test ? 

The single "parent_id" field and the "title" field are bugs that I fixed some time ago.

**Comment by alexbogo** [comment]
Hi,

Here is the output of v0.3.0, its different from you have, but will try to create role and permissions

  rbac git:(main) ✗ composer require olivier127/rbac-bundle v0.3.0
./composer.json has been updated
Running composer update olivier127/rbac-bundle
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Generating autoload files
106 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [OK]
Executing script assets:install public [OK]

No security vulnerability advisories found

➜  rbac git:(main) ✗ bin/console doctrine:schema:update --dump-sql


 [WARNING] Not passing the "--complete" option to "orm:schema-tool:update" is deprecated and will not be supported when
           using doctrine/dbal 4


CREATE TABLE permission (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, tree_left INT NOT NULL, tree_right INT NOT NULL, INDEX IDX_E04992AA727ACA70 (parent_id), INDEX permission_idx (code, tree_left, tree_right), UNIQUE INDEX unique_code (code, parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE user_role (user_id INT NOT NULL, role_id INT NOT NULL, INDEX IDX_2DE8C6A3A76ED395 (user_id), INDEX IDX_2DE8C6A3D60322AC (role_id), PRIMARY KEY(user_id, role_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE role (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, tree_left INT NOT NULL, tree_right INT NOT NULL, INDEX IDX_57698A6A727ACA70 (parent_id), INDEX permission_idx (code, tree_left, tree_right), UNIQUE INDEX unique_code (code, parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE role_permission (role_id INT NOT NULL, permission_id INT NOT NULL, INDEX IDX_6F7DF886D60322AC (role_id), INDEX IDX_6F7DF886FED90CCA (permission_id), PRIMARY KEY(role_id, permission_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE permission ADD CONSTRAINT FK_E04992AA727ACA70 FOREIGN KEY (parent_id) REFERENCES permission (id) ON DELETE CASCADE;
ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3A76ED395 FOREIGN KEY (user_id) REFERENCES sysuser (id) ON DELETE CASCADE;
ALTER TABLE user_role ADD CONSTRAINT FK_2DE8C6A3D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE;
ALTER TABLE role ADD CONSTRAINT FK_57698A6A727ACA70 FOREIGN KEY (parent_id) REFERENCES role (id) ON DELETE CASCADE;
ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE;
ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE;
➜  rbac git:(main) ✗

**Comment by alexbogo** [comment]
Hi,

Not sure what is going on, but the issue is the same...

➜  rbac git:(main) ✗ bin/console security:rbac:install

 ! [NOTE] Role permission installation


In ExceptionConverter.php line 114:

  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value


In Exception.php line 28:

  SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value


In Connection.php line 70:

  SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value


security:rbac:install

**Comment by alexbogo** [comment]
Hi, 

Yes, the v0.3.0 works great for me.  I must confess, the "title" came from my extended entity, ( left over from a previous install ) sorry for that, I have removed it now... 
Anyway, the fresh install worked as expected. I can add permissions as:

/object1/read
/object1/write
/object1/delete

No issues with parent_id. I'll do more tests in the controller and twig, but it will work fine now.

1		root	root	0	7
2	1	Object1	object1	1	4
3	1	Object2	object2	5	6
4	2	write	write	2	3


Thank you so much for fixing this.  I'll let you know how it goes.

Cheers
Alex

**Comment by Olivier127** [comment]
Hello i close this issue :)
